services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3000/api/v1
      - VITE_LINKEDIN_OAUTH_URL=http://localhost:3000/api/v1/oauth/linkedin
      - VITE_MICROSOFT_OAUTH_URL=http://localhost:3000/api/v1/oauth/microsoft
    ports:
      - 5173:5173
    volumes:
      - .:/app
    restart: always
    develop:
      watch:
        - action: rebuild
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
